/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Radiant Software (64-bit)
    2025.2.0.48.0
    Soft IP Version: 2.4.0
    2026 01 31 21:12:27
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module spiControllerbase (miso_i, sclk_o, mosi_o, ssn_o, clk_i, rst_n_i, int_o,
    ahbl_hsel_i, ahbl_hready_i, ahbl_haddr_i, ahbl_hburst_i, ahbl_hsize_i,
    ahbl_hmastlock_i, ahbl_hprot_i, ahbl_htrans_i, ahbl_hwrite_i,
    ahbl_hwdata_i, ahbl_hreadyout_o, ahbl_hresp_o, ahbl_hrdata_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  miso_i;
    output  sclk_o;
    output  mosi_o;
    output  [0:0]  ssn_o;
    input  clk_i;
    input  rst_n_i;
    output  int_o;
    input  ahbl_hsel_i;
    input  ahbl_hready_i;
    input  [5:0]  ahbl_haddr_i;
    input  [2:0]  ahbl_hburst_i;
    input  [2:0]  ahbl_hsize_i;
    input  ahbl_hmastlock_i;
    input  [3:0]  ahbl_hprot_i;
    input  [1:0]  ahbl_htrans_i;
    input  ahbl_hwrite_i;
    input  [31:0]  ahbl_hwdata_i;
    output  ahbl_hreadyout_o;
    output  ahbl_hresp_o;
    output  [31:0]  ahbl_hrdata_o;
endmodule